<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 08-May-18
 * Time: 6:37 PM
 */

$url_page = $_SESSION['url-page'];
$error_no = "2";

if ($_GET['submit'] == "add"){

    $department = $_GET['department'];
    $school = $_GET['school'];
    $add_department = "INSERT INTO `department` (`department`,`schoolID`, `statusID`) VALUES ('$department','$school','1')";
   $result = $conn->query($add_department);

}elseif ($_GET['submit'] == "status"){
    $id=$_GET['detail'];
    $status = $_GET['status'];
    $update="UPDATE `department` SET `statusID`='$status' WHERE (`departID`='$id') LIMIT 1";
    $result = $conn->query($update);

}elseif ($_GET['submit'] == "delete"){

    $id = $_GET['detail'];
    $delete = "DELETE FROM `department` WHERE (`departID`='$id')";
    $result = $conn->query($delete);

}elseif ($_GET['submit'] == "update"){

    $id = $_GET['department-code'];
    $department = $_GET['department'];
    $update = "UPDATE `department` SET `department`='$department' WHERE (`departID`='$id') LIMIT 1";
    $result = $conn->query($update);
}

if (!isset($result)){
    header("location: page.php?page=".$url_page."&token={$_SESSION['user-token']}&box=4&msg=9");
}else{
    if ($result === TRUE){
        header("location: page.php?page={$url_page}&token={$_SESSION['user-token']}&box=2&msg={$error_no}");
    }else{
        header("location: page.php?page=".$url_page."&token={$_SESSION['user-token']}&box=4&msg=9");
    }
}

