<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 16-May-18
 * Time: 10:16 PM
 */

//$pg = $_SESSION['user-page-url'];
$url_page = $_SESSION['url-page'];
$error_no = "2";


if ($_GET['submit'] == 'add') {

    $date = $_GET['date'];
    $student = $_GET['student'];
    $semester = $_GET['semester'];
    $academic = $_GET['academic-year'];
    $course = $_GET['course'];
    $level = $_GET['programme-level'];

    $add = "INSERT INTO `enrollment` (`enroll_date`, `studentID`, `semesterID`, `yearID`, `progID`,`s_level`) VALUES ('$date', '$student','$semester', '$academic', '$course','$level')";
    $result = $conn->query($add);
    $id = $conn->insert_id;

}elseif ($_GET['submit'] == 'update'){
    $id = $_SESSION['enroll-id'];
    $date = $_GET['date'];
    $student = $_GET['student'];
    $semester = $_GET['semester'];
    $academic = $_GET['academic-year'];
    $course = $_GET['course'];
    $level = $_GET['programme-level'];

    $add = "UPDATE `enrollment` SET `enroll_date`='$date', `studentID`='$student', `semesterID`='$semester', `yearID`='$academic', `progID`='$course', `s_level`='$level' WHERE (`enrollID`='$id') LIMIT 1";
    $result = $conn->query($add);

}elseif ($_GET['submit'] == 'delete'){

    $id = $_GET['detail'];
    $delete = "DELETE FROM `enrollment` WHERE (`enrollID`='$id')";
    $result = $conn->query($delete);

}

if (!isset($result)){
    header("location: {$_SESSION['user-page-url']}?page=".$url_page."&token={$_SESSION['user-token']}&box=4&msg=9");
}else{
    if ($result === TRUE){
        header("location: {$_SESSION['user-page-url']}?page={$url_page}&token={$_SESSION['user-token']}&box=2&msg={$error_no}&detail={$id}");
    }else{
        header("location: {$_SESSION['user-page-url']}?page=".$url_page."&token={$_SESSION['user-token']}&box=4&msg=9");
    }
}

