<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 08-May-18
 * Time: 6:25 PM
 */
$url_page = $_SESSION['url-page'];
$error_no = "2";

if ($_GET['submit'] == "add"){
    $school = $_GET['school'];
    $prefix = $_GET['prefix'];
    $catID = $_GET['cat'];

    if ($_GET['cat'] == 1){

        $add = "INSERT INTO `school` (`school`, `prefix`,`statusID`,`catID`) VALUES ('$school', '$prefix','1','$catID')";
        $result = $conn->query($add);

    }elseif($_GET['cat'] == 2){

        $add = "INSERT INTO `school` (`school`, `prefix`,`statusID`,`catID`) VALUES ('$school', '$prefix','1','$catID')";
        $result = $conn->query($add);

    }


}elseif($_GET['submit'] == "status"){
    //enable and disable
    $id = $_GET['detail'];
    $status = $_GET['status'];
    $update = "UPDATE `school` SET `statusID`='$status' WHERE (`schoolID`='$id') LIMIT 1";
    $result = $conn->query($update);

}elseif ($_GET['submit'] == "delete"){
    $id = $_GET['detail'];
    $delete = "DELETE FROM `school` WHERE (`schoolID`='$id')";
    $result = $conn->query($delete);

}elseif ($_GET['submit'] == 'update'){
     $id = $_GET['school-code'];
    $school = $_GET['school'];
    $prefix = $_GET['prefix'];

   $update = "UPDATE `school` SET `school`='$school', `prefix`='$prefix' WHERE (`schoolID`='$id') LIMIT 1";
    $result = $conn->query($update);
}

if (!isset($result)){
    header("location: page.php?page=".$url_page."&box=4&msg=9");
}else{
    if ($result === TRUE){
        header("location: page.php?page={$url_page}&box=2&msg={$error_no}");
    }else{
        header("location: page.php?page=".$url_page."&box=4&msg=9");
    }
}

