<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 20-May-18
 * Time: 10:56 AM
 */

$url_page = $_SESSION['url-page'];
$error_no = "2";

if ($_GET['submit'] == "add"){

    $id = $_SESSION['profile-ID'];
    $year = $_GET['year'];
    $school = $_GET['school'];
    $qualification = $_GET['qualification'];

    $add = "INSERT INTO `staff_qualification` (`profileID`,`year`, `school`, `qualification`) VALUES ('$id', '$year', '$school','$qualification')";
    $result = $conn->query($add);
}

if (!isset($result)){
    header("location: page.php?page=".$url_page."&box=4&msg=9");
}else{
    if ($result === TRUE){
        header("location: page.php?page={$url_page}&box=2&msg={$error_no}");
    }else{
        header("location: page.php?page=".$url_page."&box=4&msg=9");
    }
}
