<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 06-Mar-18
 * Time: 12:25 AM
 */

$url_page = $_SESSION['url-page'];
$error_no = "2";

if (isset($_POST['submit'])){
    $submit = $_POST['submit'];
}elseif (isset($_GET['submit'])){
    $submit = $_GET['submit'];
}else{
    echo "submit error";
}

    if ( $submit == 'add'){

        //$user_toke = uniqid();
        $date= date("Y-m-d");
        $f_name = ucfirst($_POST['first-name']);
        $l_name = ucfirst($_POST['surname']);
        $admission = ucwords($_POST['admission-number']);
        $email = $_POST['email'];
        $mobile1 = $_POST['mobile-1'];
        $mobile2 = $_POST['mobile-2'];
        $programme = $_POST['programme'];
        $year = $_POST['year'];
        $category = $_POST['category'];
        $stream = $_POST['stream'];
        $campus = $_POST['campus-status'];

        $check_student = "SELECT * FROM get_student_index_list WHERE admissionNo = '\"$admission\"'";
        $check = $conn->query($check_student);
        $check_result = $check->fetch_assoc();

        if ($check_result['admissionNo'] == $admission){
            $_SESSION['admission-no'] = $admission;
            $data = "first-name=".$f_name.
                    "&surname=".$l_name.
                    "&admission-number=".$admission.
                    "&email=".$email.
                    "&mobile-1=".$mobile1.
                    "&mobile-2=".$mobile2.
                    "&programme=".$programme.
                    "&year=".$year.
                    "&category=".$category.
                    "&stream=".$stream.
                    "&campus-status=".$campus;
            header("location: page.php?page={$url_page}&box=4&msg=10&{$data}");
            exit();
        }else{
            //if picture inserted
            $file= $_FILES['image'];
            $file_name = $_FILES['image']['name'];
            $file_tmp_name = $_FILES['image']['tmp_name'];
            $file_size = $_FILES['image']['size'];
            $file_error = $_FILES['image']['error'];
            $file_type = $_FILES['image']['type'];

            $fileExt = explode('.', $file_name);
            $file_actualExt = strtolower(end($fileExt));
            $allowed =  array ('jpg','jpeg', 'png','bmp');
            if (in_array($file_actualExt, $allowed)){
                if($file_error === 0){
                    if ($file_size < 1000000 ){
                        $file_new_name = uniqid('',true).".".$file_actualExt;
                        $file_destination = "uploads/student/".$file_new_name;
                        move_uploaded_file($file_tmp_name,$file_destination);

                        $add_data = "INSERT INTO `student_profile` (`admissionDate`, `first_name`, `surname`, `admissionNo`, `mobile1`, `mobile2`, `email`, `progID`, `yearID`, `categoryID`, `stream`, `campus_status`,`picture`) VALUES ('$date', '$f_name', '$l_name', '$admission', '$mobile1', '$mobile2', '$email', '$programme', '$year', '$category', '$stream', '$campus','$file_destination')";
                        $result = $conn->query($add_data);
                        $error_no = "2";
                    }else{
                        //echo"file is to large to upload";
                        header("location: page.php?page=".$url_page."&box=3&msg=2");
                    }
                }else{
                    //echo"there was an error uploading the file";
                    header("location: page.php?page=".$url_page."&box=3&msg=6");
                }
            }else{
                //echo"you can nout upload this kind of file";
                header("location: page.php?page=".$url_page."&box=3&msg=7");
            }
            //check student index
        }

    }elseif ($submit === "add-admission.index"){

        $date= date("Y-m-d");
        $serial = $_POST['admission-number'];
        $f_name = ucfirst($_POST['first-name']);
        $l_name = ucfirst($_POST['surname']);
        //$admission = ucwords($_POST['admission-number']);
        $email = $_POST['email'];
        $mobile1 = $_POST['mobile-1'];
        $mobile2 = $_POST['mobile-2'];
        $programme = $_POST['programme'];
        $academic_year = $_POST['year'];
        $category = $_POST['category'];
        $stream = $_POST['stream'];
        $campus = $_POST['campus-status'];

       // $input_data = md5($f_name."".$l_name."".$serial);

       $check_student = "SELECT * FROM get_student_profile_detail WHERE serial_no = '$serial'";
        $check = $conn->query($check_student);
        $check_result = $check->fetch_assoc();

        //echo $check_result['picture'];

        if ($check_result > 0){
            //echo"data exit in database";
            header("location: page.php?page={$url_page}&id={$_SESSION['student-id']}&box=4&msg=10");
        }else{
            //echo"data dont exit in database";

            $year = substr($academic_year,0,4);

            $program_prefix = "SELECT * FROM get_programme where progID = '$programme'";
            $prefix_result = $conn->query($program_prefix);
            $prefix = $prefix_result->fetch_assoc();
            $prefix_index = $prefix['prog_prefix'];

            if (!isset($prefix_index) Or empty($prefix_index)){
                
                $data = "first-name=".$f_name.
                    "&surname=".$l_name.
                    "&email=".$email.
                    "&mobile-1=".$mobile1.
                    "&mobile-2=".$mobile2.
                    "&programme=".$programme.
                    "&year=".$year.
                    "&category=".$category.
                    "&stream=".$stream.
                    "&campus-status=".$campus.
                    "&serial=".$serial;
                header("location: page.php?page={$url_page}&box=4&msg=10&{$data}");

            }else{
                $count_student = "SELECT * FROM get_total_student WHERE yearID = '\"$academic_year\"' AND progID='$programme'";
                $result_count = $conn->query($count_student);
                $count_total = $result_count->fetch_assoc();

                $student_total = $count_total['total_student'];

                if (!isset($student_total) || empty($student_total) || $student_total == 0){
                    $student_total =  1;
                    $admission = $prefix_index."".$programme."".$year."".$stream."000".$student_total;
                }else{
                    $student_total = $count_total['total_student'] + 1;
                    $unit = strlen($student_total);
                    switch ($unit){
                        case 1:
                            $admission = $prefix_index."".$programme."".$year."".$stream."000".$student_total;
                            break;
                        case 2:
                            $admission = $prefix_index."".$programme."".$year."".$stream."00".$student_total;
                            break;
                        case 3:
                            $admission = $prefix_index."".$programme."".$year."".$stream."0".$student_total;
                            break;
                        case 1:
                            $admission = $prefix_index."".$programme."".$year."".$stream."".$student_total;
                            break;
                    }

                }
                //echo $admission;

                $file= $_FILES['image'];
                $file_name = $_FILES['image']['name'];
                $file_tmp_name = $_FILES['image']['tmp_name'];
                $file_size = $_FILES['image']['size'];
                $file_error = $_FILES['image']['error'];
                $file_type = $_FILES['image']['type'];

                $fileExt = explode('.', $file_name);
                $file_actualExt = strtolower(end($fileExt));
                $allowed =  array ('jpg','jpeg', 'png','bmp');
                if (in_array($file_actualExt, $allowed)){
                    if($file_error === 0){
                        if ($file_size < 1000000 ){
                            $file_new_name = uniqid('',true).".".$file_actualExt;
                            $file_destination = "uploads/student/".$file_new_name;
                            move_uploaded_file($file_tmp_name,$file_destination);

                            $add_data = "INSERT INTO `student_profile` (`admissionDate`, `first_name`, `surname`, `admissionNo`, `mobile1`, `mobile2`, `email`, `progID`, `yearID`, `categoryID`, `stream`, `campus_status`,`picture`,`serial_no`) 
VALUES ('$date', '$f_name', '$l_name', '$admission', '$mobile1', '$mobile2', '$email', '$programme', '$academic_year', '$category', '$stream', '$campus','$file_destination','$serial')";
                            $result = $conn->query($add_data);
                            $error_no = "2";
                            $url_page = "student-list";

                        }else{
                            //echo"file is to large to upload";
                            header("location: page.php?page=".$url_page."&box=3&msg=2");
                        }
                    }else{
                        //echo"there was an error uploading the file";
                        header("location: page.php?page=".$url_page."&box=3&msg=6");
                    }
                }else{
                    //echo"you can nout upload this kind of file";
                    header("location: page.php?page=".$url_page."&box=3&msg=7");
                }
            
            }

        }
        
    }elseif ($submit == 'update'){

        $date= date("Y-m-d");
        $id = $_SESSION['student-id'];
        $f_name = $_POST['first-name'];
        $l_name = $_POST['surname'];
        $admission = $_POST['admission-number'];
        $email = $_POST['email'];
        $mobile1 = $_POST['mobile-1'];
        $mobile2 = $_POST['mobile-2'];
        $programme = $_POST['programme'];
        $year = $_POST['year'];
        $category = $_POST['category'];
        $stream = $_POST['stream'];
        $campus = $_POST['campus-status'];

         $update= "UPDATE `student_profile` SET `first_name`='$f_name', `surname`='$l_name', `admissionNo`='$admission', `mobile1`='$mobile1', `mobile2`='$mobile2', `email`='$email', `progID`='$programme', `yearID`='$year', `categoryID`='$category', `stream`='$stream', `campus_status`='$campus' WHERE (`studentID`='$id') LIMIT 1";
        $result = $conn->query($update);

    }elseif ($submit =='delete'){

       // $delete="DELETE FROM `student_profile` WHERE (`studentID`='$id')";
       // $result = $conn->query($delete);
       // $error_no = "2";
    }
/**
if (!isset($result)){
    header("location: page.php?page=" . $url_page . "&box=4&msg=9");
}else{
    if ($result === TRUE) {
        header("location: page.php?page={$url_page}&box=2&msg={$error_no}");
    } else {
        header("location: page.php?page=" . $url_page . "&box=4&msg=9");
    }
}
**/