<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 06-Mar-18
 * Time: 12:25 AM
 *
 */

$url_page = $_SESSION['url-page'];
$error_no = "2";


    if ($_POST['submit'] == 'add'){

        //$user_toke = uniqid();
        $date= date("Y-m-d");
        $f_name = $_POST['first-name'];
        $l_name = $_POST['surname'];
        $admission = $_POST['admission-number'];
        $email = $_POST['email'];
        $mobile1 = $_POST['mobile-1'];
        $mobile2 = $_POST['mobile-2'];
        $programme = $_POST['programme'];
        $year = $_POST['year'];
        $category = $_POST['category'];
        $stream = $_POST['stream'];
        $campus = $_POST['campus-status'];

            //if picture inserted
            $file= $_FILES['image'];
            $file_name = $_FILES['image']['name'];
            $file_tmp_name = $_FILES['image']['tmp_name'];
            $file_size = $_FILES['image']['size'];
            $file_error = $_FILES['image']['error'];
            $file_type = $_FILES['image']['type'];

            $fileExt = explode('.', $file_name);
            $file_actualExt = strtolower(end($fileExt));
            $allowed =  array ('jpg','jpeg', 'png','bmp');

            if (in_array($file_actualExt, $allowed)){
                if($file_error === 0){
                    if ($file_size < 1000000 ){
                        $file_new_name = uniqid('',true).".".$file_actualExt;
                        $file_destination = "uploads/student/".$file_new_name;
                        move_uploaded_file($file_tmp_name,$file_destination);

                        $add_data = "INSERT INTO `student_profile` (`admissionDate`, `first_name`, `surname`, `admissionNo`, `mobile1`, `mobile2`, `email`, `progID`, `yearID`, `categoryID`, `stream`, `campus_status`,`picture`) VALUES ('$date', '$f_name', '$l_name', '$admission', '$mobile1', '$mobile2', '$email', '$programme', '$year', '$category', '$stream', '$campus','$file_destination')";
                        $result = $conn->query($add_data);
                        $error_no = "2";
                    }else{
                        //echo"file is to large to upload";
                        header("location: page.php?page=".$url_page."&box=3&msg=2");
                    }
                }else{
                    //echo"there was an error uploading the file";
                    header("location: page.php?page=".$url_page."&box=3&msg=6");
                }
            }else{
                //echo"you can nout upload this kind of file";
                header("location: page.php?page=".$url_page."&box=3&msg=7");
            }

    }elseif ($_POST['submit'] == 'update'){

        $date= date("Y-m-d");
        $id = $_SESSION['student-id'];
        $f_name = $_POST['first-name'];
        $l_name = $_POST['surname'];
        $admission = $_POST['admission-number'];
        $email = $_POST['email'];
        $mobile1 = $_POST['mobile-1'];
        $mobile2 = $_POST['mobile-2'];
        $programme = $_POST['programme'];
        $year = $_POST['year'];
        $category = $_POST['category'];
        $stream = $_POST['stream'];
        $campus = $_POST['campus-status'];

        echo $update= "UPDATE `student_profile` SET `first_name`='$f_name', `surname`='$l_name', `admissionNo`='$admission', `mobile1`='$mobile1', `mobile2`='$mobile2', `email`='$email', `progID`='$programme', `yearID`='$year', `categoryID`='$category', `stream`='$stream', `campus_status`='$campus' WHERE (`studentID`='$id') LIMIT 1";
        $result = $conn->query($update);

    }elseif ($_POST['submit'] =='delete'){

        $delete="DELETE FROM `student_profile` WHERE (`studentID`='$id')";
        $result = $conn->query($delete);
        $error_no = "2";
    }

if (!isset($result)){
    header("location: page.php?page=".$url_page."&box=4&msg=9");
}else{
    if ($result === TRUE){
        header("location: page.php?page={$url_page}&box=2&msg={$error_no}");
    }else{
        header("location: page.php?page=".$url_page."&box=4&msg=9");
    }
}
