<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 11-May-18
 * Time: 12:29 PM
 */

if (isset($_GET['submit'])){
    $submit = $_GET['submit'];
}elseif (isset($_POST['submit'])){
    $submit = $_POST['submit'];
}

$url_page = $_SESSION['url-page'];

if ($submit == "add-block"){

    $block = $_GET['name'];
    $add = "INSERT INTO `hostel_block` (`block_name`) VALUES ('$block')";
    $result = $conn->query($add);

    $error_no = "2";

}elseif ($submit == "add-room"){

    $block = $_GET['block'];
    $room = $_GET['room'];
    $bed = $_GET['number-bed'];

    $add ="INSERT INTO `hostel_room` (`blockID`, `room`, `bed`) VALUES ('$block', '$room', '$bed')";
    $result = $conn->query($add);

    $error_no = "2";
}elseif ($submit == "add-booking"){

    $date = $_GET['date'];
    $student = $_GET['student'];
    $room = $_GET['room'];
    $yearID = $_GET['academic-year'];
    $ref = $_GET['ref-no'];
    $bed_no = $_GET['bed-no'];
    $book_in = $_GET['book-in'];
    //$book_out = $_GET['book-out'];

    $add="INSERT INTO `hostel_detail` (`tran_date`,`date`, `studentID`, `roomID`, `book_in`,`ref_no`,`bed_no`,`yearID`) 
    VALUES ('$now','$date', '$student', '$room', '$book_in','$ref','$bed_no','$yearID')";
    $result = $conn->query($add);

    $error_no = "2";

}elseif ($submit == "update-booking"){

    $rowID = $_SESSION['row-id'];
    $room = $_GET['room'];
    $ref = $_GET['ref-no'];
    //$bed = '$_GET['bed-no'];
    $book_in = $_GET['book-in'];
    $book_out = $_GET['book-out'];

    if (!empty($_GET['book-out'])){
        $update = "UPDATE `hostel_detail` SET  `roomID`='$room', `book_in`='$book_in', `book_out`='$book_out', `status`='2' WHERE (`userID`='$rowID') LIMIT 1";
        $result = $conn->query($update);
    }else{
        $update = "UPDATE `hostel_detail` SET  `roomID`='$room', `book_in`='$book_in' WHERE (`userID`='$rowID') LIMIT 1";
      $result = $conn->query($update);
    }
    $error_no = "2";

}elseif ($submit == "add-rental"){

    $date = $_POST['date'];
    $group = $_POST['name-of-group'];
    $address = $_POST['contact-address'];
    $mobile1 = $_POST['mobile-1'];
    $mobile2 = $_POST['mobile-2'];
    $rental_type = $_POST['rental-type'];
    $population = $_POST['population'];
    $ref = $_POST['ref-number'];
    $start_date = $_POST['start-date'];
    $end_date = $_POST['end-date'];
    $amount = $_POST['bill-amount'];
    $discount = $_POST['discount'];

  echo  $add = "INSERT INTO `hostel_rental` (`refNo`, `tranDate`, `church_name`, `people`,`start_date`,`end_date`,`amount`,`discount`,`mobile1`,`mobile2`,`rental_typeID`,`contact_address`)
     VALUES ('$ref', '$date', '$group', '$population','$start_date','$end_date','$amount','$discount','$mobile1','$mobile2','$rental_type','$address')";
    $result = $conn->query($add);

    $error_no = "2";

}elseif ($submit == "edit-rental"){

    $id = $_SESSION['rental-id'];
    $date = $_POST['date'];
    $group = $_POST['name-of-group'];
    $address = $_POST['contact-address'];
    $mobile1 = $_POST['mobile-1'];
    $mobile2 = $_POST['mobile-2'];
    $rental_type = $_POST['rental-type'];
    $population = $_POST['population'];
    $ref = $_POST['ref-number'];
    $start_date = $_POST['start-date'];
    $end_date = $_POST['end-date'];
    $amount = $_POST['bill-amount'];
    $discount = $_POST['discount'];
    $status =$_POST['status'];

    $update = "UPDATE `hostel_rental` SET `refNo`='$ref', `tranDate`='$date', `church_name`='$group', `people`='$population', `amount`='$amount', `discount`='$discount', `start_date`='$start_date', 
    `end_date`='$end_date', `statusID`='$status', `contact_address`='$address',`mobile1`='$mobile1',`mobile2`='$mobile2',`rental_typeID`='$rental_type' WHERE (`rentalID`='$id')";
    $result = $conn->query($update);

    $error_no = "2";


}elseif ($submit == "del-rental"){

    $id = $_GET['id'];
    $del = "DELETE FROM `hostel_rental` WHERE (`rentalID`='$id')";
    $result = $conn->query($del);

    $error_no = "2";

}elseif($submit == 'status-rental'){

    $rental = $_GET['id'];
    $days = $_GET['days'];

    $sql ="UPDATE `hostel_rental` SET `NoOfdays`='$days', `statusID`='2' WHERE (`rentalID`='$rental')";
    $result = $conn->query($sql);

    $error_no = "2";
}

if (!isset($result)){
    header("location: hostel.php?page=".$url_page."&token={$_SESSION['user-token']}&box=4&msg=9");
}else{
    if ($result === TRUE){
        header("location: hostel.php?page={$url_page}&token={$_SESSION['user-token']}&box=2&msg={$error_no}&id={$id}");
    }else{
        header("location: hostel.php?page=".$url_page."&token={$_SESSION['user-token']}&box=4&msg=9");
    }
}

