<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 10-May-18
 * Time: 4:32 PM
 */

$url_page = $_SESSION['url-page'];
$error_no = "2";

if (isset($_GET['submit'])){
    $submit = $_GET['submit'];
}else{
    $submit = $_POST['submit'];
}

if( $submit === "add-new-item"){

    $category = $_GET['category'];
    $item = $_GET['item-name'];
    $item_code = $_GET['item-code'];

    $add = "INSERT INTO `stock_main` (`categoryID`, `code_no`, `stock`) VALUES ('$category', '$item', '$item_code')";
    $result = $conn->query($add);

}elseif($submit ==="edit-item-name"){

    $id = $_SESSION['item-id'];
    $category = $_GET['category'];
    $item = $_GET['item-name'];
    $item_code = $_GET['item-code'];
    $status = $_GET['status'];

    $edit = "UPDATE `stock_main` SET `categoryID`='$category', `code_no`='$item_code', `stock`='$item', `status`='$status' WHERE (`stockID`='$id')";
    $result = $conn->query($edit);
    $edit="1";

}elseif($submit == "add-order"){

    $date = $_GET['order-date'];
    $item = $_GET['item'];
    $detail = $_GET['details'];
    $ref = $_GET['ref-no'];
    $qty = $_GET['qty'];
    $department = $_GET['department'];
    $remark = $_GET['remark'];
    $status = "1"; // mean the post is a purchase order

    $add ="INSERT INTO `stock_details` (`sys_date`, `tran_date`, `stockID`,`ref_no`, `order_qty`,`remarks`,`departmentID`,`details`,`status`) 
    VALUES ('$now', '$date', '$item', '$ref','$qty','$remark','$department','$detail','$status')";
    $result = $conn->query($add);

}elseif($submit == "add-request"){

    $date = $_GET['order-date'];
    $item = $_GET['item'];
    $detail = $_GET['details'];
    $ref = $_GET['ref-no'];
    $qty = $_GET['qty'];
    $department = $_GET['department'];
    $remark = $_GET['remark'];
    $status = "1"; // mean the post is a request

    $add ="INSERT INTO `stock_details` (`sys_date`, `tran_date`, `stockID`,`ref_no`, `order_qty`,`remarks`,`departmentID`,`details`,`status`) 
    VALUES ('$now', '$date', '$item', '$ref','$qty','$remark','$department','$detail','$status')";
    $result = $conn->query($add);

}elseif ($submit == "add-purchase"){

    $date = $_GET['date'];
    $supplyID = $_GET['supplier'];
    $item = $_GET['item'];
    $qty = $_GET['qty'];
    $ref = $_GET['ref'];
    $price = $_GET['price'];

    $status = "2";

    $add ="INSERT INTO `stock_details` (`sys_date`, `tran_date`, `stockID`,`ref_no`, `purchase_qty`,`status`,`supplyID`,`unit_price`) 
    VALUES ('$now', '$date', '$item', '$ref','$qty','$status','$supplyID','$price')";
    $result = $conn->query($add);

}elseif ($submit == "add-issused"){

    $date = $_GET['date'];
    $staff = $_GET['staff'];
    $item = $_GET['item'];
    $ref = $_GET['ref'];
    $qty = $_GET['qty'];
    $comment = $_GET['comment'];

    $stock_qty ="SELECT * FROM `get_total_issused` WHERE stockID = '$item'";
    $qty_result = $conn->query($stock_qty);
    $qty_bal =$qty_result->fetch_assoc();

     $qty_available = $qty_bal['bal'];

      if ($qty_available > $qty){
        $add ="INSERT INTO `stock_details` (`sys_date`, `tran_date`, `stockID`,`ref_no`, `issue_qty`,`staffID`,`details`,`status`) 
   VALUES ('$now', '$date', '$item', '$ref','$qty','$staff','$comment','3')";
    $result = $conn->query($add);

    }else{

         header("location: store.php?page=".$url_page."&token={$_SESSION['user-token']}&box=4&msg=15");
         exit(0);
    }

      

}elseif($submit === 'add-category'){

    $category = $_GET['category-name'];
    $add = "INSERT INTO `stock_category` (`category_name`, `stateID`) VALUES ('$category', '1')";
    $result = $conn->query($add);

}elseif($submit ==='add-supplier-contact'){
    
    $supplier = $_GET['supplier-name'];
    $address = $_GET['address'];
    $mobile1 = $_GET['mobile1'];
    $mobile2 = $_GET['mobile2'];
    $email = $_GET['email'];

    $add = "INSERT INTO `supplier_contact` (`supplier_name`, `address`, `mobile1`, `mobile2`, `email`) 
    VALUES ('$supplier', '$address', '$mobile1', '$mobile2', '$email')";
    $result = $conn->query($add);

}elseif($submit ==="edit-supplier-contact"){

    $id = $_SESSION['supplier-id'];
    $supplier = $_GET['supplier-name'];
    $address = $_GET['address'];
    $mobile1 = $_GET['mobile1'];
    $mobile2 = $_GET['mobile2'];
    $email = $_GET['email'];

   $edit = "UPDATE `get_supplier_contact` SET `supplier_name`='$supplier', `address`='$address', `mobile1`='$mobile1', `mobile2`='$mobile2', `email`='$email' WHERE (`supplyID`='$id')";
    $result = $conn->query($edit);

}

if (!isset($result)){
    header("location: store.php?page=".$url_page."&token={$_SESSION['user-token']}&box=4&msg=9");
}else{
    if ($result === TRUE){
        if (isset($edit)){
            header("location: store.php?page={$url_page}&token={$_SESSION['user-token']}&detail={$id}&box=2&msg={$error_no}");
        }else{
            header("location: store.php?page={$url_page}&token={$_SESSION['user-token']}&box=2&msg={$error_no}");
        }

    }else{
        header("location: store.php?page=".$url_page."&token={$_SESSION['user-token']}&box=4&msg=9");
    }
}
