<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 15-May-18
 * Time: 10:14 PM
 */

function enrollment($conn,$id){
    $sql="SELECT * FROM get_enrollment WHERE  studentID = '$id'";
    $result=$conn->query($sql);
    while ($r=$result->fetch_assoc()){
        echo"
           <tr>
                <td class='center'>
                    <label class='pos-rel'>
                        <input type='checkbox' class='ace' />
                            <span class='lbl'></span>
                    </label>
                </td>

                <td>
                    <a href='#'>{$r['enroll_date']}</a>
                </td>
                <td>{$r['yearID']}</td>
                <td class='hidden-480'>{$r['calendar']}</td>
                <td class='hidden-480'>
                    {$r['course']}
                </td>

                <td>
                    <div class='hidden-sm hidden-xs btn-group'>
                        <button class='btn btn-xs btn-success'>
                            <i class='ace-icon fa fa-check bigger-120'></i>
                        </button>

                        <button class='btn btn-xs btn-info'>
                            <i class='ace-icon fa fa-pencil bigger-120'></i>
                        </button>

                        <button class='btn btn-xs btn-danger'>
                            <i class='ace-icon fa fa-trash-o bigger-120'></i>
                        </button>

                        <button class='btn btn-xs btn-warning'>
                            <i class='ace-icon fa fa-flag bigger-120'></i>
                        </button>
                    </div>
                </td>
           </tr> 
        ";

    }
}

function student_profile_enrollment($conn,$id){

    $sql="SELECT * FROM `get_student_enrollment` WHERE studentID = '$id'";
    $result=$conn->query($sql);
    while ($r=$result->fetch_assoc()){

        echo "
            <tr>
                    <td class='center'>
                        <label class='pos-rel'>
                            <input type='checkbox' class='ace' />
                            <span class='lbl'></span>
                        </label>
                    </td>

                    <td>
                        {$r['enroll_date']}
                    </td>
                    <td>{$r['yearID']}</td>
                    <td>{$r['semester']}</td>
                    <td>{$r['admissionNo']} - {$r['first_name']} {$r['surname']}</td>

                    <td class='hidden-480'>
                         {$r['programme']} / {$r['prefix']}
                    </td>

                    <td>
                        <div class='hidden-sm hidden-xs action-buttons'>
                            <a class='red' href='model.php?ui=enrollment&submit=delete&detail={$r['enrollID']}'>
                                <i class='ace-icon fa fa-trash-o bigger-130'></i>
                            </a>
                        </div>
                    </td>
                </tr>
        ";
    }
}
